### ISSUE TITLE
Check specification of model with interaction

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/ROC22_CovVaxComparativeSafety#5]

**Comment by edward-burn** [comment]
At the moment it seems to be including month, but I think we just want age*gender

**Comment by Xintong-Li-ZnCu** [comment]
> 
"All incidence rates and effect size estimate (where applicable) will be stratified by sex, 10-year age band, calendar month, and vaccine type (where applicable). "

**Comment by Xintong-Li-ZnCu** [comment]
> At the moment it seems to be including month, but I think we just want age*gender

"All incidence rates and effect size estimate (where applicable) will be stratified by sex, 10-year age band, calendar month, and vaccine type (where applicable). "

**Comment by edward-burn** [comment]
@Xintong-Li-ZnCu But doesn´t that sentence imply we would have an estimate per sex/age/month? Eg Estimated incidence among 60-69 year old in March 2021?
